//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace phoenix.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("phoenix.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;pre style=&quot;overflow-x:auto;word-wrap: break-word;&quot;&gt;
        ///Copyright 2015 - Helios Interactive
        ///301 8th St. Suite 250, San Francisco, CA 94103
        ///
        ///This is a proprietary technology, meant solely to be used by clients of Helios Interactive. If you have received this software in error or by accident please delete it immidiately.
        ///
        ///This software comes as-is and its source code is available and will be furnished upon request without any preconditions to the authorized clients of Helios Interactive as mentioned above. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string about {
            get {
                return ResourceManager.GetString("about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;log4net&gt;
        ///    &lt;appender name=&quot;PhoenixRollingFile&quot; type=&quot;log4net.Appender.RollingFileAppender&quot;&gt;
        ///        &lt;file value=&quot;phoenix.log&quot; /&gt;
        ///        &lt;appendToFile value=&quot;true&quot; /&gt;
        ///        &lt;maximumFileSize value=&quot;1MB&quot; /&gt;
        ///        &lt;maxSizeRollBackups value=&quot;20&quot; /&gt;
        ///
        ///        &lt;layout type=&quot;log4net.Layout.PatternLayout&quot;&gt;
        ///            &lt;conversionPattern value=&quot;%5level [%2thread] [%21logger@%3line] - %message%newline&quot; /&gt;
        ///        &lt;/layout&gt;
        ///    &lt;/appender&gt;
        ///    &lt;root&gt;
        ///        &lt;level value=&quot;ALL&quot; /&gt;
        ///        &lt;appender-r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string logger {
            get {
                return ResourceManager.GetString("logger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /helios/phoenix.
        /// </summary>
        internal static string MqttTopic {
            get {
                return ResourceManager.GetString("MqttTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] rsync {
            get {
                object obj = ResourceManager.GetObject("rsync", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
